# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MCDVisualizer
                                 A QGIS plugin
 Mars Climate Database (MCD) visualizer in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-16
        copyright            : (C) 2025 by David Sánchez
        email                : david.sanchezruiz@edu.uah.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MCDVisualizer class from file MCDVisualizer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mcd_visualizer import MCDVisualizer
    return MCDVisualizer(iface)
